version: "3.6"

services:
  my-table-control-db-postgres:
    image: bitnami/postgresql:latest
    restart: always
    container_name: my-table-control-db-postgres
    ports:
      - ${PG_PORT}:5432
    environment:
      POSTGRESQL_USERNAME: "${PG_USER}"
      POSTGRESQL_PASSWORD: "${PG_PASSWORD}"
      PGPASSWORD: "${PG_PASSWORD}"
      POSTGRESQL_DATABASE: "${PG_DB_NAME}"
    volumes:
      - my-table-control-volume:/bitnami/postgresql

volumes:
  my-table-control-volume:
